version: '3.7'

services:
  timesheet-generator:
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - "5111"
    volumes:
      - ./timesheet-generator:/app/data
    networks:
      - caddy-proxy_caddy

networks:
  caddy-proxy_caddy:
    external: true