version: '3.7'

services:
  timesheet-generator:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./timesheet-generator:/app/data
    networks:
      - caddy-adguard_caddy

networks:
  caddy-proxy_caddy:
    external: true